version: 0.2

phases:
  install:
    runtime-versions:
        php: 7.3
  pre_build:
    commands:
        - echo "Running Pre-Build script..."
        - printenv DB_NAME
        - printenv DB_USER
        - printenv DB_PASSWORD
        - printenv DB_HOST